### ISSUE TITLE
Név bekérése

### ISSUE THREAD

**Issue by rekaehreth** [Freya2001/gyakorlas#1]
Módosítsd a korábban megírt programot úgy, hogy a szám bekérése előtt kérdezze meg a felhasználótól, mi a neve, és b+-ek helyett passzív aggresszív módon szólítsa meg a felhasználót. (E.g. `Ezt te sem gondoltad komolyan, kedves Réka :)` )
A páros-páratlan eldöntésénél is játszd el ugyanezt. (E.g. `A 7 páros, de ezt magadtól is tudod, kedves Edit ^_^` )

**Comment by Freya2001** [comment]
Megold.: [1ab057250fab307880a61d7aada173b4dd5478e4](https://github.com/Freya2001/gyakorlas/commit/1ab057250fab307880a61d7aada173b4dd5478e4)
