### ISSUE TITLE
Milyen napra esik

### ISSUE THREAD

**Issue by rekaehreth** [Freya2001/gyakorlas#2]
Kérj egy számot a felhasználótól 1 és 28 között, majd számold ki, hogy 2021 februárjában a bekért dátum milyen napra esik. 
(Pl. 8-a hétfő)

**Comment by Freya2001** [comment]
Megoldas: [20e8a7ea90eb388bf19320ca95a077377bb361b0](https://github.com/Freya2001/gyakorlas/commit/20e8a7ea90eb388bf19320ca95a077377bb361b0)
